version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  fhir:
    image: hapiproject/hapi:v5.3.0
    container_name: hapi_fhir_server
    ports:
      - "8080:8080"
    environment:  
      profiles.active: r4
      spring.datasource.url: jdbc:postgresql://db:5432/hapi
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
    depends_on: 
      - db

  db:
    image: postgres
    container_name: pgserver2
    environment:  
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hapi
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  fhir-agent:
    build:
      context: ../src/agents
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyDmLe0kNW2DpR69QJC8jprZ1m_ueClutVY
      - GEMINI_AI_MODEL=gemini-2.0-flash
      - RABBITMQ_HOST=rabbitmq
      - HAPI_FHIR_VALIDATOR_URL=http://fhir:8080/fhir/StructureDefinition
      - FHIR_SERVER_URL=http://fhir:8080/fhir
    depends_on:
      - rabbitmq
      - fhir

volumes:
  rabbitmq_data: {}
  postgres_data: {}
